### ISSUE TITLE
Error when execute the build script

### ISSUE THREAD

**Issue by vanvuongngo** [jatinhemnani01/extension-with-svelte#1]
What is the purpose of this command? `cpx -C public/** public/**`
I got an error message and when I remove it then the build runs successfully.
![image](https://user-images.githubusercontent.com/20791239/121104127-a7c28e00-c801-11eb-80f6-ab7c863b0276.png)

**Comment by jatinhemnani01** [comment]
You can't run 'npm run dev' in this template. You can create new svelte app and eject the source folder in this template or you can build every time you want to see changes. 
Will try to fix
